unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf recarregado"

set -g prefix C-s
unbind C-b
bind C-s send-prefix

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Status bar
set -g status-position top

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

# Dracula
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-show-flags true

# Dracula modules
set -g @dracula-plugins "weather"

# Weather
set -g @dracula-fixed-location "-23.5228,-46.1883"
set -g @dracula-show-fahrenheit false

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
