editor nvim

font_size 12.0

font_family      JetBrainsMono Nerd
bold_font        JetBrainsMono Nerd Bold
italic_font      JetBrainsMono Nerd Italic
bold_italic_font JetBrainsMono Nerd Bold Italic

background_opacity 0.8
dynamic_background_opacity yes
hide_window_decorations yes

window_padding_width 15

shell tmux new-session -A -s main
